name: ClickTpa
version: 1.7.1
main: com.jklmao.plugin.ClickTpa
authors: [ jklmao ]
description: Simple TPA plugin for Spigot/Paper Software

commands:
  tpa:
    usage: /<command>
    aliases: [teleport]
  tpahere:
    usage: /<command>
  tpaccept:
    usage: /<command>
    aliases: [tpyes]
  tpadeny:
    usage: /<command>
    aliases: [tpdeny, tpno]
  tpo:
    usage: /<command>
    alises: [tp]
  tpohere:
    usage: /<command>
    aliases: [s, tphere]
  tptoggle:
    usage: /<command>
  tpacancel:
    usage: /<command>
    aliases: [tpcancel]
  clicktparl:
    usage: /<command>
    aliases: [ctparl]
